grails-app/controllers/shiyaokeji_erp/InvoiceTypeController.groovy
package shiyaokeji_erp




import constant.SystemConstant

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class InvoiceTypeController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def afterInterceptor = {
        session.setAttribute(SystemConstant.UserNowInHeadMenuKEY, '发票管理')
        session.setAttribute(SystemConstant.UserNowInChildMenuKEY, '发票类别')
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond InvoiceType.list(params), model: [invoiceTypeInstanceCount: InvoiceType.count()]
    }

    def show(InvoiceType invoiceTypeInstance) {
        respond invoiceTypeInstance
    }

    def create() {
        respond new InvoiceType(params)
    }

    @Transactional
    def save(InvoiceType invoiceTypeInstance) {
        if (invoiceTypeInstance == null) {
            notFound()
            return
        }

        if (invoiceTypeInstance.hasErrors()) {
            respond invoiceTypeInstance.errors, view: 'create'
            return
        }

        invoiceTypeInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'invoiceTypeInstance.label', default: 'InvoiceType'), invoiceTypeInstance.id])
                redirect invoiceTypeInstance
            }
            '*' { respond invoiceTypeInstance, [status: CREATED] }
        }
    }

    def edit(InvoiceType invoiceTypeInstance) {
        respond invoiceTypeInstance
    }

    @Transactional
    def update(InvoiceType invoiceTypeInstance) {
        if (invoiceTypeInstance == null) {
            notFound()
            return
        }

        if (invoiceTypeInstance.hasErrors()) {
            respond invoiceTypeInstance.errors, view: 'edit'
            return
        }

        invoiceTypeInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'InvoiceType.label', default: 'InvoiceType'), invoiceTypeInstance.id])
                redirect invoiceTypeInstance
            }
            '*' { respond invoiceTypeInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(InvoiceType invoiceTypeInstance) {

        if (invoiceTypeInstance == null) {
            notFound()
            return
        }

        invoiceTypeInstance.delete flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'InvoiceType.label', default: 'InvoiceType'), invoiceTypeInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'invoiceTypeInstance.label', default: 'InvoiceType'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/invoiceType/_form.gsp
<%@ page import="shiyaokeji_erp.InvoiceType" %>



<div class="fieldcontain ${hasErrors(bean: invoiceTypeInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="invoiceType.name.label" default="Name" />
		
	</label>
	<g:textField name="name" value="${invoiceTypeInstance?.name}"/>
</div>

grails-app/views/invoiceType/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin_layout">
		<g:set var="entityName" value="${message(code: 'invoiceType.label', default: 'InvoiceType')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-invoiceType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-invoiceType" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${invoiceTypeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${invoiceTypeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:invoiceTypeInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/invoiceType/edit.gsp
<%@ page import="shiyaokeji_erp.InvoiceType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin_layout">
		<g:set var="entityName" value="${message(code: 'invoiceType.label', default: 'InvoiceType')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-invoiceType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-invoiceType" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${invoiceTypeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${invoiceTypeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:invoiceTypeInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${invoiceTypeInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/invoiceType/index.gsp
<%@ page import="shiyaokeji_erp.InvoiceType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin_layout">
		<g:set var="entityName" value="${message(code: 'invoiceType.label', default: 'InvoiceType')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-invoiceType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-invoiceType" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table class="table table-bordered">
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'invoiceType.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'invoiceType.dateCreated.label', default: 'Date Created')}" />

					</tr>
				</thead>
				<tbody>
				<g:each in="${invoiceTypeInstanceList}" status="i" var="invoiceTypeInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${invoiceTypeInstance.id}">${fieldValue(bean: invoiceTypeInstance, field: "name")}</g:link></td>
					
						<td><g:formatDate date="${invoiceTypeInstance.dateCreated}" /></td>
					

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${invoiceTypeInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/invoiceType/show.gsp
<%@ page import="shiyaokeji_erp.InvoiceType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin_layout">
		<g:set var="entityName" value="${message(code: 'invoiceType.label', default: 'InvoiceType')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-invoiceType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-invoiceType" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list invoiceType">
			
				<g:if test="${invoiceTypeInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="invoiceType.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${invoiceTypeInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${invoiceTypeInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="invoiceType.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${invoiceTypeInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${invoiceTypeInstance?.invoices}">
				<li class="fieldcontain">
					<span id="invoices-label" class="property-label">包含发票的创建时间</span>
					
						<g:each in="${invoiceTypeInstance.invoices}" var="i">
						<span class="property-value" aria-labelledby="invoices-label"><g:link controller="invoice" action="show" id="${i.id}">${i?.dateCreated.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>

			</ol>
			<g:form url="[resource:invoiceTypeInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${invoiceTypeInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>